import express from "express";
import cors from "cors";
import multer from "multer";
import crypto from "node:crypto";
import { OllamaService } from "./services/llm/ollama.service.js";
import { AssistantService } from "./services/orchestration/assistant.service.js";
import { IngestionService } from "./services/rag/ingestion.service.js";
import { RetrievalService } from "./services/rag/retrieval.service.js";
import { ToolManager } from "./services/tools/tool-manager.js";
import { calculatorTool } from "./services/tools/calculator.tool.js";
export const app = express(); app.use(cors()); app.use(express.json());
const retrieval=new RetrievalService();
const assistant=new AssistantService(undefined, undefined, retrieval);
const ingestion=new IngestionService(), tools=new ToolManager(); tools.register(calculatorTool);
const documents = new Map<string,{id:string;name:string;createdAt:string}>();
app.get("/api/health", async (_req,res)=>res.json({ok:true, ollama:await new OllamaService().healthCheck()}));
app.post("/api/chat", async (req,res,next)=>{try { const {message,conversationId="default"}=req.body||{}; if(!message) return res.status(400).json({error:"message is required"}); res.json(await assistant.chat(message,conversationId)); } catch(e){next(e)}});
app.post("/api/documents/upload", multer({storage:multer.memoryStorage()}).single("file"), (req,res)=>{if(!req.file)return res.status(400).json({error:"file is required"}); const id=crypto.randomUUID(); documents.set(id,{id,name:req.file.originalname,createdAt:new Date().toISOString()}); retrieval.add(ingestion.ingest(id,req.file.buffer.toString("utf8"))); res.status(201).json(documents.get(id));});
app.get("/api/documents", (_req,res)=>res.json([...documents.values()]));
app.delete("/api/documents/:id",(req,res)=>{documents.delete(req.params.id); retrieval.remove(req.params.id); res.status(204).end()});
app.post("/api/documents/search",(req,res)=>res.json(retrieval.search(req.body?.query||"",req.body?.limit||5)));
app.get("/api/conversations/:id",(req,res)=>res.json(assistant.getMemory(req.params.id)));
app.post("/api/memory/search",(req,res)=>res.json(assistant.getMemory(req.body?.conversationId||"default")));
app.get("/api/tools",(req,res)=>res.json(tools.list()));
app.post("/api/tools/execute",async(req,res,next)=>{try{res.json(await tools.execute(req.body.name,req.body.input))}catch(e){next(e)}});
app.use((err:Error,_req:express.Request,res:express.Response,_next:express.NextFunction)=>res.status(500).json({error:err.message||"Internal error"}));
